# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ vars.OS }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: xcodebuild test -scheme StackUIKit -destination '${{ vars.DESTINATION }}'
